name: Standart Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Check wokeness
      uses: get-woke/woke-action@v0
      with:
        # Cause the check to fail on any broke rules
        fail-on-error: true
          
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -o flowagent .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: binary
        path: ./flowagent
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: flowkeeper
        password: ${{ secrets.DOCKER_APPLICATION_SECRET }}
        
    - name: Build docker image and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: flowkeeper/flowagent:${{ github.ref }}
    
    
